#!/bin/bash

#==========================
# Set up the environment
#==========================
set -e                  # exit on error
set -o pipefail         # exit on pipeline error
set -u                  # treat unset variable as error

export LC_ALL=C
export LANG=en_US.UTF-8
export DEBIAN_FRONTEND=noninteractive

Green="\033[32m"
Red="\033[31m"
Yellow="\033[33m"
Blue="\033[36m"
Font="\033[0m"
GreenBG="\033[42;37m"
RedBG="\033[41;37m"
OK="${Green}[  OK  ]${Font}"
ERROR="${Red}[FAILED]${Font}"
WARNING="${Yellow}[ WARN ]${Font}"

function print_ok() {
  echo -e "${OK} ${Blue} $1 ${Font}"
}

function print_error() {
  echo -e "${ERROR} ${Red} $1 ${Font}"
}

function print_warn() {
  echo -e "${WARNING} ${Yellow} $1 ${Font}"
}

function judge() {
  if [[ 0 -eq $? ]]; then
    print_ok "$1 succeeded"
  else
    print_error "$1 failed"
    exit 1
  fi
}

# List of URLs to fetch IP lists
ip_urls=(
  'https://raw.githubusercontent.com/stamparm/ipsum/master/levels/3.txt'
  'https://gitlab.aiursoft.cn/anduin/ShameList-HackersIPs/-/raw/master/list'
  # Add more URLs as needed
)

ipsetname=ufw-blocklist-ipsum
ipset_exe=/usr/sbin/ipset
tmpfile=$(mktemp)

# Ensure the ipset exists
print_ok "Ensure $ipsetname exists..."
$ipset_exe -t list "$ipsetname" &>/dev/null
judge "Check if ipsetname exists"

# Download and concatenate the lists
print_ok "Downloading IP lists and concatenating..."
for url in "${ip_urls[@]}"; do
  curl -sS -f --compressed "$url" >> "$tmpfile" || print_warn "Failed to download from $url"
done
judge "Download and concatenate lists"

# Remove duplicates
print_ok "Removing duplicates..."
rawlist=$(sort -u "$tmpfile")
judge "Remove duplicates"

print_ok "Removing temporary file..."
rm -f "$tmpfile"
judge "Remove temporary file"

print_ok "Parsing the list..."
declare -a scrublist
readarray -t scrublist < <(echo "$rawlist")
judge "Parse the list"

print_ok "Create temporary ipset..."
tmpsetname="$(mktemp -u | cut -f2 -d'.')-tmp"
$ipset_exe -q create "$tmpsetname" hash:net
judge "Create temporary ipset"

print_ok "Adding IPs to temporary ipset..."
cnt=0
for i in "${scrublist[@]}"; do
  $ipset_exe add "$tmpsetname" "$i" && print_ok "Added $i to $tmpsetname" || print_warn "Failed to add $i to $tmpsetname"
  cnt=$((cnt+1))
done

print_ok "Swap temporary ipset with $ipsetname..."
$ipset_exe swap "$tmpsetname" "$ipsetname"
judge "Swap temporary ipset with $ipsetname"

print_ok "Destroy temporary ipset..."
$ipset_exe -q destroy "$tmpsetname"
judge "Destroy temporary ipset"

print_ok "Finished updating $ipsetname. New count: $cnt"
